default:
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: data-pipeline-project-445905
      dataset: dbt_vkv
      location: EU
      threads: 5
      keyfile: /path/to/your-service-account-key.json
  target: dev
