
version: 2

models:
    - name: clean_sales
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: clean_customers
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
sources:
  - name: raw
    database: data-pipeline-project-445905  # Specify your database name here
    schema: big_query_id  # Specify your schema (dataset) name here
    tables:
      - name: raw_sales  # Define the table as raw_sales
        description: "Raw sales data table"
      - name: raw_customers  # Define the table as raw_customers
        description: "Raw customers data table"
      - name: raw_products  # Define the table as raw_products
        description: "Raw products data table"